version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "6306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - ./php/my.cnf:/etc/mysql/my.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8082:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
  web:
    image: php:7.4-apache
    container_name: php74
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    build:
      context: ./php
      dockerfile: Dockerfile
    links:
      - db
    depends_on:
      - db
volumes:
  dbdata:
